name: demo-project CI

on:
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  IMAGE_TAG: "V1.0.${{ github.run_number }}"

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-eclipse-temurin-17-alpine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          cd demo-project
          mvn test

  build_and_push:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: demo-project
          file: demo-project/Dockerfile
          push: true
          tags: thejurist/simplex:${{ env.IMAGE_TAG }}

  update_helm_repo:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout Helm Repository
        uses: actions/checkout@v3
        with:
          repository: Djurizt/simplex
          token: ${{ secrets.GH_PAT }}

      - name: Update Image Tag in Helm Chart
        run: |
          cd demo-project
          sed -i 's/tag:.*/tag: ${{ env.IMAGE_TAG }}/' ./chart/values.yaml
          git config user.email "gbebejunior@gmail.com"
          git config user.name "Djurizt"
          git add ./chart/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
      
      - name: Push Image Tag Update to Helm Repo
        run: git push origin main
