name: CI/CD Pipeline

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:
env:
  IMAGE_TAG: "V1.0.${{ github.run_number }}"
  
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-eclipse-temurin-17-alpine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Run Tests
        run: |
          cd demo-project
          mvn test

  # sonar_analysis:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: sonarsource/sonar-scanner-cli:5.0.1
  #   env:
  #     CI: 'true'
  #     scannerHome: '/opt/sonar-scanner'
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
      
  #     - name: Run SonarQube Analysis
  #       run: |
  #         $scannerHome/bin/sonar-scanner
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build_and_push:
    runs-on: ubuntu-latest
    # needs: [testing, sonar_analysis]
    needs: [testing]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Build and Push Docker Image
        run: |
          cd demo-project
          docker build -t thejurist/simplex:${{ env.IMAGE_TAG }} .
          docker push thejurist/simplex:${{ env.IMAGE_TAG }}

  update_helm_repo:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout Helm Repository
        run: |
          rm -rf simplex || true
          git clone https://github.com/Djurizt/simplex.git
      
      - name: Update Image Tag in Helm Chart
        run: |
          cd simplex/demo-project
          sed -i 's/tag:.*/tag: ${{ env.IMAGE_TAG }}/' ./chart/values.yaml
          git config user.email "gbebejunior@gmail.com"
          git config user.name "Djurizt"
          git add ./chart/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
      - name: Push image to GitHub
        run: |
          cd simplex
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Djurizt/simplex.git main

